### PR TITLE
Support zoxide for jumping

### PR DESCRIPTION
**Pull request by toadle**
There is even more autojump-clones. I like to use https://github.com/ajeetdsouza/zoxide because it supports querying it's database and some other things.

I though I'd add another plugins to use it in nnn.

### CODE REVIEW

**Comment by jarun** [comment]
Please add the functionality to the `autojump` plugin. It already supports autojump and jump.

**Comment by toadle** [comment]
@jarun Oh, you are right. Didn't notice that. I'll change it and submit a fix.

**Comment by jarun** [comment]
Thanks!

**Comment by toadle** [comment]
@jarun New version!

BTW: I noticed that when calling

```
curl -Ls https://raw.githubusercontent.com/jarun/nnn/master/plugins/getplugs | sh
```

while having `nnn` 3.4 will not get me the plugins from `master´-branch, but rather some version-specific stuff. So I won't get the current `autojump`-plugin. That was the root cause for me not seeing that `autojump` supports several scripts already.

**Comment by jarun** [comment]
> while having nnn 3.4 will not get me the plugins from master-branch

That's correct. We can't always support new plugins with older releases so the plugins are release-fixed.

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
@toadle I have added some minor modifications at 57163ffa5de7c2c8ab136e5f50ac56a7ce0dac7c.

**Pull request merged**
