### PR TITLE
preview-tui: shell escape filenames being fed to eval

### PR DESCRIPTION
**Pull request by N-R-K**
Fixes: https://github.com/jarun/nnn/issues/1614

### CODE REVIEW

**Comment by N-R-K** [comment]
Tested on filenames with spaces and parenthesis.

@amalgame21 please confirm if this fixes all your test cases or not.

**Comment by amalgame21** [comment]
For filename only, seems ok, will test it when I back home.
For folder name (I mean current directory), probably not because the `$PWD` and `$PREVIEW_MODE` will contain current directory name which is a part of `$ENVSTRING`.

**Comment by N-R-K** [comment]
> For folder name (I mean current directory), probably not because the `$PWD` and `$PREVIEW_MODE` will contain current directory name which is a part of `$ENVSTRING`.

Hmm, good call. I'll test it out soon (and fix if needed).

**Comment by luukvbaal** [comment]
Do we think https://github.com/jarun/nnn/pull/1580 was worth it? It seems figuring out workarounds for that change and the way to properly pass the environment variables to a newly support preview may be more work than simply copying the list of variables again.

If `preview-tui` was written in bash we could have used a proper array of variables but this POSIX sh array I used seems to have downsides. Not sure if worth it...

**Comment by luukvbaal** [comment]
I'm not to keen on creating a subshell for each envvar we have to escape. It noticeably increases the time for the first preview to show up.

If we can't figure out a way that avoids that and preferably even the for loop to begin with, I think I'd rather revert the refactor part of https://github.com/jarun/nnn/pull/1580.

**Comment by amalgame21** [comment]
Tested, working fine, thanks for you work! But it seems slower than before.
Understand it is hard to do in POSIX, hope it is easier using `bash` array.
The `finder` plugin also require bash ,which is the first example in the nnn [plugin](https://github.com/jarun/nnn/tree/master/plugins) page.

**Comment by N-R-K** [comment]
> But it seems slower than before.

Spawning a subshell for each env var will do that :)

I think we should either just use bash (it has builtin substitution with `${var/s/r}` and has real arrays) or revert the refactor part of the other commit.

**Comment by luukvbaal** [comment]
Yeah I started converting to bash arrays a while ago but got sidetracked on other OS work :)

**Pull request closed without merging**
