### PR TITLE
Fix restorepreview patch conflict

### PR DESCRIPTION
**Pull request by luukvbaal**
Don't merge this yet if you want to consider https://github.com/jarun/nnn/issues/1348#issuecomment-1140349482, adding that would reintroduce the conflict for this patch.

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
Sorry, I missed your note and the label. It's OK. Please raise the PR along with the patch correction.

**Comment by jarun** [comment]
@luukvbaal can you please modify CI script to apply the patches and confirm everything works on each commit?

Also, please add a section in the [Wiki developer guides](https://github.com/jarun/nnn/wiki/Developer-guides) on how to fix the patch conflicts.

**Comment by jarun** [comment]
And link to the section in misc/CONTRIBUTING.md.

**Comment by jarun** [comment]
> Also, please add a section in the [Wiki developer guides](https://github.com/jarun/nnn/wiki/Developer-guides) on how to fix the patch conflicts.

> And link to the section in misc/CONTRIBUTING.md.

On second thoughts, the right place is the patch README.

**Comment by luukvbaal** [comment]
Sure, I'll look into it. The way I resolve the patch conflicts currently is to:
- `git checkout` the feature branch on my fork for the specific patch
- `git rebase` which will fail with merge conflicts
- edit the merge conflicts around the git markers manually
- `git add` -> `git rebase --continue`
- Then `git diff HEAD^` will again result in the updated patch which I copy to `patches/<patchname>/<patch>.diff

I could update the developer guide with this but the problem is that these feature branches currently live on my fork.

**Comment by luukvbaal** [comment]
git(and the feature branches) are not strictly necessary here though. 

One could also make do with just make a copy of the latest master `nnn.c`. Then `patch --merge nnncopy.c <patch.diff>` instead of `git rebase`, fix the merge conflicts and then run `diff <nnncopy.c> <master>` instead of `git diff HEAD^`. 

I use git and the feature branches to be able to easily checkout and build a single patch. Not sure whats best to put on the wiki.

**Comment by jarun** [comment]
The second option is better.

**Comment by luukvbaal** [comment]
> > Also, please add a section in the [Wiki developer guides](https://github.com/jarun/nnn/wiki/Developer-guides) on how to fix the patch conflicts.
> 
> > And link to the section in misc/CONTRIBUTING.md.
> 
> On second thoughts, the right place is the patch README.

Should the entire section on how to fix patch conflicts go into patches README, or just the link the link to the wiki?

**Comment by jarun** [comment]
The entire section. Nothing in WIki.

**Pull request merged**
