### PR TITLE
print_details: printw align

### PR DESCRIPTION
**Pull request by luukvbaal**
Seems more elegant to me than the `blanks` solution unless there is some other downside to using `printw()` I'm not aware of?

Was looking for a solution to avoid the print loop in my name first patch https://github.com/luukvbaal/nnn/commit/4deec222abf9aebaeb09778218d12404802c79f1 where the `blanks` solution can't be applied and thought I would suggest it for upstream as well.

### CODE REVIEW

**Comment by jarun** [comment]
printw() parses the format string and passes the result to addstr(). I wanted to get rid of it (as much as possible) so we can avoid the formatting checks.

**Comment by jarun** [comment]
Accidentally closed. Reopened and merged. Thanks!

**Comment by luukvbaal** [comment]
> printw() parses the format string and passes the result to addstr(). I wanted to get rid of it (as much as possible) so we can avoid the formatting checks.

I see, can you explain why you merged it in this case? Do you expect it to be faster than the multiple `addstr()/addch()` calls?

**Comment by luukvbaal** [comment]
If I had seen this commit https://github.com/jarun/nnn/commit/ed23e494a9064eb29879cfd9c24fa4965f1ea4d4 before I wouldn't have made this PR in the first place. I do wonder why you think it's better in this case(assuming you do since you merged it).

**Comment by jarun** [comment]
Yes, I think the performance difference is negligible given we do not have any numeric to string conversion.

**Comment by luukvbaal** [comment]
I see, thanks for the insight!

**Comment by jarun** [comment]
Also see commit 903a4b3a66bb37a029906ef20b97ca68619a5310. Reduces many lines of code and the numeric conversions are only for values < 99 so I guess the performance would be similar even if the naive approach is taken.

**Pull request merged**
