### PR TITLE
Fix preview-tui-ext and ueberzug support for preview-tui

### PR DESCRIPTION
**Pull request by luukvbaal**

### CODE REVIEW

**Comment by luukvbaal** [comment]
Feel free to delete `preview-tui-ext` if u feel that its unnecessary and up to the user to define more preview options.

**Comment by luukvbaal** [comment]
In any case I think it makes more sense to just use whats available so I got rid of the config variables  with precedence `kitty` > `ueberzug` > `catimg` > `viu`.

**Comment by jarun** [comment]
Thank you so much!

**Comment by jarun** [comment]
Thank you so much!

**Pull request merged**
