### PR TITLE
Macos 10.11

### PR DESCRIPTION
**Pull request by elder-n00b**

### CODE REVIEW

**Comment by 0xACE** [comment]
I doubt `README_FORK.md` should be included

**Comment by elder-n00b** [comment]
I am sorry, I did not even intend to make a pull request yet. I botched something. And I put a bug in the makefile -- fixed.
I'll also remove the README_FORK.md, I put it there just in case someone comes across my fork.
It's clearly unnecessary now that I bothered you with the PR, sounds like it would be accepted.

**Comment by 0xACE** [comment]
I practically didn't review the changes at all, just scrolled and saw `README_FORK.md`.

I don't know if it will get accepted. In my experience: there are very tight restrictions on what gets merged into `nnn`...

Quick glance:
- some of your files are missing a newline character at the end of the file.
- why are `#include` directors given before include guards?

**Comment by jarun** [comment]
Please explain the issue and the fix.

**Comment by 0xACE** [comment]
> Please explain the issue and the fix.

Just to speed things up im making a guess: I think he is supplying a patch for old macos versions that didnt support `clock_gettime` or w/e... I think we had discussions about this in the past.

Have a good weekend XOXO

**Comment by elder-n00b** [comment]
Thanks for head up about the newlines.

About the includes, I only added this:
```
#ifdef MACOS1011
#include "mach_gettime.h"
#endif
```
where `MACOS1011` is defined in the makefile (didn't want to bother with the AccessibilityMacros).

Yes, as mentioned above, it's just a small workaround to make it compile on old systems.
I thought it could be useful to others on legacy hardware.

**Comment by jarun** [comment]
Got it!

**Comment by KlzXS** [comment]
I think this is fine. CI needs to be addressed first, though.

It's complaining about something in the added files and the command in Makefile. The command (`sw_vers`) is not available on linux. You should first check that the system has it using something that works on both linux and macos. And the BSDs.

I can't remember of the top of my head what was the portable solution we used. You can find an example somewhere in the project I'm sure.

**Comment by elder-n00b** [comment]
I confirm, I put that bug in the makefile. It's already fixed -- in theory. I'll double check though.

**Comment by elder-n00b** [comment]
>You can find an example somewhere in the project I'm sure.
I noticed the misc/haiku dir, I think I'll do something similar as it's more self-contained.
TBH I'm not very happy that I put the two mach_gettime files in src, they're not properly part of the project.

**Comment by jarun** [comment]
Haiku has a dedicated Makefile. For macOS I would suggest using the same Makefile.

**Comment by jarun** [comment]
See if this helps: https://stackoverflow.com/questions/8024961/c-macro-for-os-x-version-lion-or-not-detection

**Comment by jarun** [comment]
Please do not add new files.

**Comment by jarun** [comment]
Closing as we have a new PR.

**Pull request closed without merging**
