### PR TITLE
Reset less --quit-if-one-screen for NNN_PAGER default

### PR DESCRIPTION
**Pull request by czak**
This is a proposal to update the `NNN_PAGER` default command.

## Context

I've  run into the [Help not showing](https://github.com/jarun/nnn/wiki/Troubleshooting#help-not-showing) issue as I was playing with `nnn` for the first time.

My `$LESS` includes `-F`/`--quit-if-one-screen` flag, so (after finally finding #157 and the Wiki entry) I understand why it happens and how to work around it.

However, I'd like to keep the flag in my global `$LESS`.

## Proposal

What do you think about enforcing the behavior for the `NNN_PAGER` default?
According to `man less`, this can be done using `-+F`:

> If an option appears in the LESS variable, it can be reset to its default value on the command line by beginning the command line option with "-+".
> -- https://man.archlinux.org/man/less.1#OPTIONS

### CODE REVIEW

**Comment by jarun** [comment]
@N-R-K @luukvbaal any comments on this?

**Comment by N-R-K** [comment]
> I've run into the [Help not showing](https://github.com/jarun/nnn/wiki/Troubleshooting#help-not-showing) issue as I was playing with `nnn` for the first time.
> 
> My `$LESS` includes `-F`/`--quit-if-one-screen` flag, so (after finally finding #157 and the Wiki entry) I understand why it happens and how to work around it.
> 
> However, I'd like to keep the flag in my global `$LESS`.

This all seems fine in theory. However, this patch is changing the default for `preview-tui` plugin and shouldn't have any effect on the help screen (shown via <kbd>?</kbd>) - so I'm a bit confused here.

**Comment by czak** [comment]
> this patch is changing the default for `preview-tui` plugin and shouldn't have any effect on the help screen (shown via `?`)

Ayayay that's my bad :sweat: I must have tested it with a smaller window and thought it worked. Sorry about that.

I updated the fix in [42a3154](https://github.com/jarun/nnn/pull/1701/commits/42a315482d0c3cbe696ffc94e772c03a5a8dd933). It works, but I don't really like this change anymore. The other `utils[]` don't set flags (except for `rm -rf` and `sh -c`), so it feels a bit out of place here.

Please feel free to decide what is best here.
Thank you for taking a look.

**Comment by N-R-K** [comment]
`UTIL_LESS` affects a lot more than just the help screen. I don't think we can merge this without exhaustive testing to make sure it doesn't cause regression elsewhere.

**Comment by czak** [comment]
I'll just go ahead and close it. Maybe it will be useful as reference for others who run into the issue. Thanks!

**Pull request closed without merging**
