### PR TITLE
preview-tui: restore tree view

### PR DESCRIPTION
**Pull request by luukvbaal**

### CODE REVIEW

**Comment by jarun** [comment]
Paged tree view is OK as long as it shows like below:

```
.
├── ACT_Invoice-MAR-2020.html
├── ACT_Invoice.pdf
├── Amrita [165 entries exceeds filelimit, not opening dir]
├── Desktop
│   ├── teams.desktop
│   ├── wps-office-prometheus.desktop
│   └── Zoom.desktop
├── Documents [114 entries exceeds filelimit, not opening dir]
├── Downloads
│   ├── 08. std 1 comp.pdf
│   ├── 16. Std 1_Hindi_wrksht4.pdf
│   ├── packages
│   │   ├── anydesk_6.1.0-1_amd64.deb
│   │   ├── dropbox_2020.03.04_amd64.deb
│   │   ├── fd_8.1.1_amd64.deb
│   │   ├── fzf-0.25.1-linux_amd64.tar.gz
│   │   ├── gdu-linux-amd64.tgz
│   │   ├── glow_1.2.1_linux_amd64.deb
│   │   ├── hplip-3.20.3-plugin.run
│   │   ├── imv_4.0.1-1_amd64.deb
│   │   ├── rclone-v1.53.3-linux-amd64.deb
│   │   ├── ripgrep_12.1.1_amd64.deb
│   │   ├── teams_1.3.00.25560_amd64.deb
│   │   └── zoom_amd64.deb
│   ├── Revision - Eng Lang.pptx
...
```

**Comment by luukvbaal** [comment]
Sure, what should the limit be?

**Comment by jarun** [comment]
How about:

    fifo_pager tree --filelimit $(ls -l . | wc -l) -C -F --dirsfirst --noreport

**Comment by luukvbaal** [comment]
Yeah sounds reasonable, pushed the change.

**Comment by jarun** [comment]
Please use `ls -lf` so listing happens faster without any sorting.

**Comment by luukvbaal** [comment]
`ls -lf` causes https://www.shellcheck.net/wiki/SC2012

**Comment by jarun** [comment]
In fact, just `ls -f | wc -l`

Suppress the shellcheck stuff. It's pranoid to some extent. ;)

**Comment by luukvbaal** [comment]
There's no difference in speed for find and ls though:
```
find /usr/bin -maxdepth 1  0.00s user 0.02s system 98% cpu 0.020 total
/usr/bin/ls -f /usr/bin  0.01s user 0.01s system 98% cpu 0.020 total
```
Might as well use `find` and not cause any `shellcheck` errors.

**Comment by jarun** [comment]
Sure!

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
