### PR TITLE
Add neovim support

### PR DESCRIPTION
**Pull request by KillTheMule**
Hey!

I've added neovim support to your plugin script. I had to move some things around, but nothing fancy. I've manually tested that it still works on vim/gvim, so all should be good.

(e) Ah yeah, I've also added printing an error if the tempfile isn't readable. I'd say that's a serious error (not supposed to happen), and should be reported to the user.

### CODE REVIEW

**Comment by jarun** [comment]
Can't thank you enough! :+1:

**Comment by mcchrish** [comment]
@KillTheMule opening a file from nnn doesn't open in neovim but opens to the default program for that file type. e.g. opening a shell file opens it in xcode.

**Comment by KillTheMule** [comment]
@mcchrish Are you sure you're using it correctly? I thought so at first, but then observed the same behavior with vim, so it must be intentional. Did you press `<Enter>` on a file? That opens it in the default viewer alright, both in vim and nvim. Select the file in selection mode and quit nnn, that opens the file in nvim (just as is the behavior in vim).

**Comment by mcchrish** [comment]
@KillTheMule sorry about that. I was using an old version nnn that doesn't have the selection mode. Just updated and works now. 👍

**Comment by jarun** [comment]
> edit: agree. I think pressing `<enter>` seems more intuitive.

I can add a patch which would change the behaviour so when you press `Enter` it picks and quits.

So, normal quit would

- either copy selection if it exists (this is useful as it supports multiple selection)
- or do nothing

**Comment by KillTheMule** [comment]
Sounds about right. I'd also suggest adding a key for "whatever I selected, just quit without passing back anything". Maybe `Q` is the right for that.

**Comment by jarun** [comment]
I think it's becoming unnecessarily complex from this point. Please share a simpler workflow if you have.

**Comment by KillTheMule** [comment]
Oh, don't worry about my workflow, I don't have one since I'm not using nnn. I just threw out suggestions because of how I imagined others might be using it from (neo)vim, but feel free to totally ignore them (especially considering that you have more to consider than how one might use this from (neo)vim).

**Pull request merged**
