### PR TITLE
sxiv automatically plays animations (part2)

### PR DESCRIPTION
**Pull request by tonijarjour**
Alright I made it work on files too. The `-a` flag isn't compatible with imv, so it needs its own check for sxiv.

### CODE REVIEW

**Comment by jarun** [comment]
Ci fails. Please check.

**Comment by tonijarjour** [comment]
Alright that works

**Comment by jarun** [comment]
Can you please check if it's possible in `nuke` and `preview-tabbed` as well?

**Comment by tonijarjour** [comment]
For nuke, I did the following
`export NNN_OPENER=/home/toni/.config/nnn/plugins/nuke`
And I ran `nnn -c` then I opened the image by pressing `;v`
It did work in this case.

For preview tabbed I ran:
`NNN_FIFO=/tmp/nnn.fifo nnn`
And again using `;v` opened the gif with animations on

**Comment by jarun** [comment]
Cool! Thanks for confirming. Ci seems failing again. Please check.

**Comment by tonijarjour** [comment]
Sorry I don't know what to do. The travis Ci doesn't say whats wrong.

**Comment by KlzXS** [comment]
Travis CI seems to have some issue running the builds, seems connection related. All builds in the past 8 hours errored. :shrug:

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
