### PR TITLE
Add plugin to open all selected files in tabs in vim

### PR DESCRIPTION
**Pull request by sumanchapai**
For vim users, this is a helpful feature if you are looking to edit
multiple files then this plugin will allow you to do exactly that.

### CODE REVIEW

**Comment by jarun** [comment]
Please add the functionality to plugin `openall`.

**Comment by sumanchapai** [comment]
I am not sure what we would like to do to the existing function of openall.

**Comment by jarun** [comment]
Good. Raise the PR when you are sure.

**Comment by sumanchapai** [comment]
Could you reopen the PR? I have integrated the functionality  in `openall`

**Comment by N-R-K** [comment]
Why do we need to special case vim? AFIAK opening multiple files with vim would just open each on a new tab.

**Comment by sumanchapai** [comment]
As of now, the plugin is using a hardcoded `OPENER` variable. One of the additions in this recent commit, 
https://github.com/sumanchapai/nnn/commit/3bfe5aaa4b02ad45ef58b724391304cb0e485ee4 is that it uses `EDITOR` env variable. Additionally, to open files in tabs one needs to supply `-p` flag. But users usually have vim aliased to `vim -p`.

**Comment by N-R-K** [comment]
> One of the additions in this recent commit, [sumanchapai@3bfe5aa](https://github.com/sumanchapai/nnn/commit/3bfe5aaa4b02ad45ef58b724391304cb0e485ee4) is that it uses `EDITOR` env variable.

I don't think that's how the plugin is meant to be used. $OPENER is supposed to deal with the file-type and open it in a suitable application. The way you commit works, is it'll try an open *any type* of file with vim if `$EDITOR` is set to vim, which is certainly not a good behavior.

**Comment by sumanchapai** [comment]
Thank you for elaborating. Looks like the nuke plugin handles my requested use case.

**Pull request closed without merging**
