### PR TITLE
nerdfont support for chess files(pgn,fen) haskell(hs,lhs) files and hpp

### PR DESCRIPTION
**Pull request by CantoroMC**
If this pr is accepted, do you like if a provide some other changes to nerdfont icons?
Also, i would like to ask .....
I really like more the previous current item and selection indicators, if I provide a pr to reintroduce them with a compiler flag, will it be accepted, or have you decided to stick with the current method?

### CODE REVIEW

**Comment by jarun** [comment]
Thanks for the PR!

> do you like if a provide some other changes to nerdfont icons?

> I really like more the previous current item and selection indicators

Please remind me what was the previous current indicator.

By previous selection indicator do you mean just the `+` without reverse for selection?

Please share the details.

@luukvbaal please review this.

**Comment by CantoroMC** [comment]
The previous indicator were > for the current item and + for the selection.
The selection has now also reversed colors which I don't like (I asked cause I understand that my taste may not be shared).

**Comment by jarun** [comment]
I would like to leave the current indicator as it is because it's much easier to find the hovered line.

For the selection marker I initially chose bold `+`.
However, switched to the current style because it's only temporary and it's much easier to find visually.

**Comment by CantoroMC** [comment]
Yes of course. Thanks again.

**Comment by jarun** [comment]
Thank you!

**Comment by luukvbaal** [comment]
Thanks for extending the icon list, looks good to me.

I must say I'm also not a big fan of the inverse current/selection indicators. I did like the change to bold which I guess I will be using on my personal builds.

**Comment by jarun** [comment]
Bold doesn't work for people who disable it in the terminal.

**Pull request merged**
