### PR TITLE
Compile static bin locally for release

### PR DESCRIPTION
**Pull request by maximbaz**
So now you will just do `make upload-local` and it will do the rest.

Is this something you had in mind?

### CODE REVIEW

**Comment by jarun** [comment]
Exactly! Thank you!

**Comment by jarun** [comment]
Oops! I missed something. Can you also package the static binary in tar.gz format with the release version?

**Comment by maximbaz** [comment]
Do you mean to simply wrap the binary in the archive, with no additions? I don't think archive will save any space on the binary... :slightly_smiling_face:

**Comment by jarun** [comment]
> Do you mean to simply wrap the binary in the archive, with no additions?

Yes, an archive is better.

**Comment by jarun** [comment]
I'll take care of it. No problem!

**Pull request merged**
