### PR TITLE
Enter type-to-nav for bookmarks dir

### PR DESCRIPTION
**Pull request by luukvbaal**

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
To keep the behaviour same, can you please have it for plugin selection from plugin dir as well?

**Comment by jarun** [comment]
Ignore. Too many checks.

**Comment by N-R-K** [comment]
Should update the manpage and other relevant docs imo.

**Comment by luukvbaal** [comment]
For sure, I can go over it once we finalized.

**Pull request merged**
