### PR TITLE
Add Desktop Opener for Haiku

### PR DESCRIPTION
**Pull request by CodeforEvolution**
You guys almost forgot this. Hope this helps! ;)

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
Oops! Thank you for noticing! ;)

Bad miss from my side. I'd been using `nuke` extensively to confirm it for next release and almost forgot about the default desktop opener!

**Comment by annagrram** [comment]
My bad too.
Thanks for bringing it up and fixing it :)

**Comment by jarun** [comment]
BTW, now that we are here, I'm adding `peaclock` as the terminal _locker_ for Haiku. Looks cool and the other alternatives are not available on Haiku.

**Comment by jarun** [comment]
Notifying @octobanana, the author of `peaclock` that `nnn` will use it as the default terminal _locker_ on Haiku. One of the coolest I've seen in a while.

**Comment by jarun** [comment]
It's loosely coupled though. So no need to add it as a dep.

**Pull request merged**
