### PR TITLE
Add automatic RPM builds via travis

### PR DESCRIPTION
**Pull request by fennm**

### CODE REVIEW

**Comment by fennm** [comment]
Travis has the log database down for maintenance right now so I can't see why it failed.  Will check back later.

**Comment by jarun** [comment]
Thank you so much @fennm!

**Comment by jarun** [comment]
In RHEL, is there a separate ncursesw-devel (like libncursesw in Ubuntu) or UTF-8 is also supported by ncurses-devel?

**Comment by fennm** [comment]
There's only one ncurses-devel, which provides the wide-char and 
standard-char versions of the lib:

[mfenn@fedora nnn.git]$ rpm -qf /usr/lib64/libncursesw.so
ncurses-devel-6.0-6.20160709.fc25.x86_64
[mfenn@fedora nnn.git]$ rpm -qf /usr/lib64/libncurses.so
ncurses-devel-6.0-6.20160709.fc25.x86_64

**Comment by jarun** [comment]
Tanks for confirming!

**Comment by jarun** [comment]
Is the PR ready to merge?

**Comment by fennm** [comment]
Yep, should be good to go.

**Comment by jarun** [comment]
Thank you so much!

**Comment by jarun** [comment]
It threw an error on first run:

https://travis-ci.org/jarun/nnn/jobs/226706434

**Comment by jarun** [comment]
I am adding you as a collaborator... please feel free to make the required changes.

**Comment by jarun** [comment]
Invite sent.

**Comment by jarun** [comment]
@fennm still failing.

**Comment by jarun** [comment]
Oopsss, I missed adding the key! :dagger: 

Working now. Will it be possible to generate RPMs only when there are new tag?

**Comment by fennm** [comment]
Yeah sorry about that, only owner can create deployment keys to use, I should have mentioned that.  I added a stanza to the .travis.yml to only generate releases when a tag is pushed.

**Comment by jarun** [comment]
No problem at all! Awesome!

**Pull request merged**
