### PR TITLE
Add git status column

### LINKED ISSUE #802: Feature request: status in git repos
Thank you for creating nnn!!! 

**Is your feature request related to a problem? Please describe.**

I would like to see at a glance some info when viewing git repos such as uncommitted files etc.

**Describe the solution you'd like**

It would be nice if this could be indicated via symbols/colors, preferably also with a toggle switch as done for the detail view in nnn.

**Describe alternatives you've considered**

Especially since I want to use nnn as a replacement of nerdtree in vim, it would be nice to have similar behaviour like here:
[Xuyuanp/nerdtree-git-plugin](https://github.com/Xuyuanp/nerdtree-git-plugin)

**Additional context**

Screenshot from the abohve nerdtree-git-plugin (see git status symbols on the left part of the image)
grafik

### PR DESCRIPTION
**Pull request by crides**
Potentially en route to fix #802. This PR adds a git status column using [`libgit2`](https://github.com/libgit/libgit2). The implementation is derived from [`exa`](https://github.com/ogham/exa). 

Sample screenshot (with `nnn` above and `exa` below):

maim-2021 05 20 23 18 38

The colors are a hack. They are currently taken from the builtin filetype colors, which can change based on configs. 

I don't expect this to be merged (based on the conversation in #802; certainly not now). The current version has questionable variable/function naming, though this could be turned into a compile time configurable feature. If this is not going to be merged, this can just be a reference for those few of us that are looking for such a feature.

### CODE REVIEW

**Comment by KlzXS** [comment]
Yeah, this is almost certainly not getting merged.
But I will be working on a showcase for good user patches that don't make the cut.

I'll be sure to tag you when that's up.

**Comment by jarun** [comment]
> But I will be working on a showcase for good user patches that don't make the cut.

That would be great. Note that you need to sanitize the code. I am keeping the PR open.

I remember @0xACE also had a patch to add relative numbers from the hovered file.

@luukvbaal I think this is also a good model for your patch to show file names at the beginning.

Regarding maintenance, @KlzXS please tag the owners of each patch in the Wiki page so people can look them up. And would you be kind enough to test the patches after each release to ensure they are compatible still? It's this ownership that will confirm if this model will work for top-up patches.

**Comment by crides** [comment]
I'm probably not going to actively maintain it, but yes I would be able to test it once in a while.

**Comment by jarun** [comment]
> I'm probably not going to actively maintain it, but yes I would be able to test it once in a while.

Thanks for confirming. That's exactly why I have my reservations regarding accepting large PRs from non-regular contributors.
I can't burden myself or regular contributors with the task of understanding and maintaining that extra code permanently.

I think the patch model is good if it works.

**Comment by jarun** [comment]
@crides please fix the CI issues.

**Comment by luukvbaal** [comment]
> @luukvbaal I think this is also a good model for your patch to show file names at the beginning.

I like the idea. Curious to see what you had in mind @KlzXS in terms of presenting/hosting the patches.

**Comment by KlzXS** [comment]
Well since `nnn` has such a vast presence on the internet I'm spoiled for choice. /s

No, it would have to be something in this repo for now. I'm thinking of a directory like the one for plugins, just for patches. Each patch would get it's own subdirectory to store relevant things.

**Comment by luukvbaal** [comment]
Yeah I was wondering whether a dir on the repo for patches would be welcomed by @jarun or whether the patches would have to be linked to or hosted on a patches wiki page.

**Comment by jarun** [comment]
Yes, of course! Anyway you guys like it.

I think if we go that way, we will need an automatic patch application (one by one first, followed by cumulative) logic in CI. That would save @KlzXS a lot of effort.

But I want the patches to be of high quality. So please ensure the proper cleanup and review is done before accepting any such patch.

**Comment by KlzXS** [comment]
> one by one first, followed by cumulative

What do you mean by this? I planned on patches being based on specific commits, preferably release commits. Once every release you update the patch. 

We should move this to another thread.

**Comment by jarun** [comment]
Responding in devs group.

**Comment by jarun** [comment]
@KlzXS can you please sanitize this for the patch activity?

**Comment by KlzXS** [comment]
Sure. But no sooner than a week.

**Comment by jarun** [comment]
No problem! Just wanted to make sure you didn't forget about it. ;)

**Comment by jarun** [comment]
Closing as we are getting this into patch framework.

**Comment by luukvbaal** [comment]
It seems the patch is picking up at least `nnn.1` incorrectly and different from `exa`:
image

Any idea why this would happen @crides? Also do you know of an easy way to set up a test repo containing all the git flags?

**Pull request closed without merging**
