### PR TITLE
Update README demo

### PR DESCRIPTION
**Pull request by luukvbaal**
Went ahead and made a new screencast since the current one has double width/half width(issue with my terminal which is since fixed) icons. Als made sure to show a search, detail mode and `preview-tui` paging.
previewtuidemo

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
It's a 421KiB image. Please reduce the size.
And I really prefer something less dark and catchy/funny probably.

I am reverting this. The video is awesome but we need a better image for a project front page.

**Comment by jarun** [comment]
I am making a release today. We will have this in with the new image after the release.

**Comment by Kabouik** [comment]
About darkness, are you referring to the whole gif? To me the colours, including background, look relatively standard. Or are you talking about one of the images being previewed? The image below is dark but shows how nnn handles transparency:

ss-2021-04-13_111452

I just realized thanks to the gif that we have .docx preview now, thanks! If you do another animation, maybe showing multiple contexts would be nice since the animation seems to be showcasing basic nnn features?

**Comment by jarun** [comment]
In any case, need a smaller image size. The previous one was ~250KiB. I think @luukvbaal will take care of it soon.

**Comment by luukvbaal** [comment]
@jarun
> And I really prefer something less dark and catchy/funny probably.

The image is a thumbnail of the video, do you see a timestamp of a preview you would prefer? The demo was originally on the plugins readme since it's primarily showcasing `preview-tui-ext`. Are you saying that you want another image on the project readme altogether with "catchy/funny"(whatever that means) colors or are just talking about having a different thumbnail of this video with something different in the preview pane?
If you still want the demo on the front-page but with different colors give me a theme and I'll re-record...

@Kabouik I could record a sequence including contexts yeah, depending on whether @jarun still wants it on the front-page readme as a general demo or if it's going to be a `preview` demo...

**Comment by jarun** [comment]
@luukvbaal image is fine. Please make the size smaller.

**Pull request merged**
