### PR TITLE
Remove -E from sed in plugins

### PR DESCRIPTION
**Pull request by KlzXS**
Please pass it through some light tests to see if I missed some spot.

### CODE REVIEW

**Comment by jarun** [comment]
@N-R-K can you please check?

**Comment by N-R-K** [comment]
The `xdgdefault` changes are fine, tested it out a bit. @KlzXS if you got GNU-sed try to use the `--posix` flag to disable all extension and see if everything works as expected or not. If it does then it's most likely ok.

**Comment by jarun** [comment]
@KlzXS please confirm once good to go.

**Comment by KlzXS** [comment]
I tried it out. Everything seems in order. Both with `--posix` and without.

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
