### PR TITLE
Added New Plugin

### PR DESCRIPTION
**Pull request by Zazucki**
Added upl0ad: Upload files to 0x0.st

I'm open to alternative names, or integrating this into the upload plugin.

### CODE REVIEW

**Comment by jarun** [comment]
Please integrate with the existing upload plugin.

**Comment by KlzXS** [comment]
You are right, those two don't work anymore. Remove ffsend, it's been years and it's officially discontinued. See what that new Thunderbird Send stuff is if you can. Keep ix for now, maybe it comes back.

Other than that just add the new service and offer the user to choose which one to use.

**Comment by jarun** [comment]
@Zazucki can you please address the comments?

**Comment by Zazucki** [comment]
I have seen nothing about Thunderbird Send since [this podcast](https://blog.thunderbird.net/2023/09/thunderbird-podcast-5-remote-work-tips-tricks/) from September 27, 2023. Specifically [this part](https://www.youtube.com/watch?v=zt_2xiNjQBo). I doubt it'll be available for use until they officially release the modernized Thunderbird.

ix.io has been down [since December of last year](https://web.archive.org/web/20231210021245/http://ix.io/), I'm not sure how long is acceptable to wait.
Also, according to the [most recent live version](https://web.archive.org/web/20231127094241/http://ix.io/) of ix.io:
> If you are distributing software that uses this automatically, talk to me first.

Was this ever done when initially implementing the plugin?

Other than the [Client](https://web.archive.org/web/20230620054904/ix.io/client), it seems to only have a few more features over 0x0.st, like color highlighting.

I'm fine with implementing the changes into the original upload plugin, but it may take me some time to get around to it.

**Comment by jarun** [comment]
OK, take your time. Remove ix.io as well.

**Comment by Zazucki** [comment]
Here's a first attempt, it's rough but it works. Still need to test with bad filenames.

https://gist.github.com/Zazucki/d3d843cd26053f6ff38e16082b40b4af

I know line 16 is a mess, but `xargs` complains if I try to split the line. Also, this was the only way I found it to work with selections.

If it's not clear, please ask questions.

**Comment by jarun** [comment]
@Zazucki make sure to run chellcheck.
@KlzXS can you please review?

**Comment by Zazucki** [comment]
[Shellcheck](https://www.shellcheck.net/) only found 1 problem, I fixed and updated the gist.

**Comment by jarun** [comment]
@N-R-K please review if you have the time.

**Comment by KlzXS** [comment]
I left a comment on the gist @Zazucki.

**Comment by N-R-K** [comment]
Do you guys know any pastebin which has syntax highlighting and can auto-detect language? I was looking at https://bpa.st but it doesn't seem to auto-detect filetype.

**Comment by Zazucki** [comment]
I used to use hastebin for that but I heard Toptal ruined it.

There's some promising things here you can look through:
[https://alternativeto.net/software/pastebin/](https://alternativeto.net/software/pastebin/)

**Pull request closed without merging**
