### PR TITLE
preview-tui: fix cleanup

### PR DESCRIPTION
**Pull request by luukvbaal**
Opened this by accident, still working on it...

### CODE REVIEW

**Comment by jarun** [comment]
OOPS... I missed the WIP.

**Comment by jarun** [comment]
How long would it take?

**Comment by jarun** [comment]
I will force revert.

**Comment by luukvbaal** [comment]
It's fine, there's just a small issue when resizing the window after starting `preview-tui` without changing the selection.

**Comment by luukvbaal** [comment]
Should be no need to revert.

**Pull request merged**
