### PR TITLE
preview-tui: reformat toggle

### PR DESCRIPTION
**Pull request by luukvbaal**
Reduce flickering on toggle by wrapping in function and sending to background.

Edit: just noticed I messed up the environment variables passed to `kitty`/`tmux` will fix, probably tomorrow though.

### CODE REVIEW

**Comment by luukvbaal** [comment]
This works great with `tmux` and `$TERMINAL` options but for some reason doesn't play well with `kitty`. Seems like running 
https://github.com/jarun/nnn/blob/1fc7fde819d6a7e082055ff10407f4744d862090/plugins/preview-tui#L105 and https://github.com/jarun/nnn/blob/1fc7fde819d6a7e082055ff10407f4744d862090/plugins/preview-tui#L110 from a background process sends garble to stdin for some reason, causing `nnn` to hang and the split is never opened.

**Comment by luukvbaal** [comment]
I'll see if I can figure it out but I'm wondering how do we feel about dropping `kitty` split support from `preview-tui` and instead suggest running `tmux` @jarun @leovilok?. `tmux` with `ueberzug` inside with `kitty` is way more responsive than the `kitty` splits and previews and provides a better experience in my opinion.

**Comment by luukvbaal** [comment]
> Seems like running
> https://github.com/jarun/nnn/blob/1fc7fde819d6a7e082055ff10407f4744d862090/plugins/preview-tui#L105
> 
> and
> https://github.com/jarun/nnn/blob/1fc7fde819d6a7e082055ff10407f4744d862090/plugins/preview-tui#L110
> 
> from a background process sends garble to stdin for some reason, causing `nnn` to hang and the split is never opened.

This can be avoided (tested and confirmed) using the `@ --to` but would require users to start `kitty` with the `--listen-on` flag. Any opinions on this or dropping `kitty` support?

**Comment by jarun** [comment]
> This can be avoided (tested and confirmed) using the @ --to but would require users to start kitty with the --listen-on flag. Any opinions on this or dropping kitty support?

Is the issue intermittent? I didn't face any issues with kitty when I tried it.

Also, can this be a one time setting in the kitty config file?

**Comment by luukvbaal** [comment]
It happens every time I start `preview-tui`. Interesting that it's not an issue for you, the cause is that escape codes are being printed to the terminal(see https://github.com/kovidgoyal/kitty/issues/1501) which seem to be caught as keypresses by `nnn` on my system. Unfortunately it cannot be set in the configuration file(https://github.com/kovidgoyal/kitty/issues/2557).

**Comment by luukvbaal** [comment]
Actually the man page states "For UNIX sockets, this can also be specified in kitty.conf." It is possible https://github.com/kovidgoyal/kitty/commit/85b55b31b6d4c0e22345a2593c6c04721e63af48.

**Comment by luukvbaal** [comment]
`eval KITTYSOCKET="$(awk '/^listen_on/ {print $2}' "${XDG_CONFIG_HOME}"/kitty/kitty.conf)-$(pstree -sap $$ | awk -F',' '/kitty/ { print $2; exit}')"` and  `kitty @ --to "$KITTYSOCKET"` works to extract the socket set in `kitty.conf`. 
However, I'm still curious if anyone is against dropping `kitty` support from `preview-tui` in favor of `tmux` since it works in `kitty` and is way faster.

**Comment by jarun** [comment]
Someone already using kitty may not be interested in learning tmux.

**Comment by luukvbaal** [comment]
> Someone already using kitty may not be interested in learning tmux.

Yeah I suppose, not sure what to do with this PR then. 
I really like the improvement for `tmux` and `$TERMINAL` case but doesn't seem applicable to the `kitty` previews. It works for tui previews but the `kitten icat` image preview doesn't seem to play well the `@ --to` flag. Focus goes to the preview pane and the image disappears immediately without the `--hold` flag.

**Comment by luukvbaal** [comment]
It might well be possible, I never actually used `kitty` so perhaps someone who has can assist.

**Comment by jarun** [comment]
Just install it and check it out.

**Comment by luukvbaal** [comment]
I have it installed of course to test the plugin I was just saying someone who actually uses it might have an easier time figuring it out.

**Comment by jarun** [comment]
Ahh. OK. No I hardly use previews myself.

**Comment by luukvbaal** [comment]
> Seems like running
> https://github.com/jarun/nnn/blob/1fc7fde819d6a7e082055ff10407f4744d862090/plugins/preview-tui#L105
> 
> and
> https://github.com/jarun/nnn/blob/1fc7fde819d6a7e082055ff10407f4744d862090/plugins/preview-tui#L110
> 
> from a background process sends garble to stdin for some reason, causing `nnn` to hang and the split is never opened.

I made some further changes and this issue is not present anymore, not sure what caused it unfortunately. Can be merged now as far as I'm concerned.

**Comment by jarun** [comment]
Thank you! I am sure users will get back if they see any problems. ;)

**Comment by luukvbaal** [comment]
To reiterate: this PR immediately sends `preview-tui` to the background to avoid flickering(shell prompt coming through) in the terminal window. The flickering is mostly gone on all terminals I've tested except `alacritty` which seems to draw at a higher fps and the prompt sometimes comes through, still an improvement to the old situation though.

If we want to get rid of the flicker entirely for the preview plugins I suppose we have to detach the process in `nnn` already. Probably not worth the extra logic though as we would have to make a distinction between normal plugins and plugins that only do something in the background.

**Pull request merged**
