### PR TITLE
Add gitstatus patch -G flag

### PR DESCRIPTION
**Pull request by luukvbaal**
gitstatus patch change that allows showing the git status column also outside of detail view.

### CODE REVIEW

**Comment by luukvbaal** [comment]
Lol @ these diff diffs, so readable.

**Comment by jarun** [comment]
Oh @luukvbaal, it definitely looks like you lose track of your changes in nnn without this patch. ;)

Thank you!

**Comment by luukvbaal** [comment]
Uhm not sure what that's supposed to mean(passive aggressive insult? if not never mind). Sure you can keep track of your changes without this patch. Also it wasn't my idea to begin with. I do feel it's nice to have though.

**Comment by jarun** [comment]
I was just joking about your continued efforts to get it right. Nothing bad.

**Comment by luukvbaal** [comment]
Cross-referencing #654 #802 for visibility as this PR should fix the issues.

**Pull request merged**
