### PR TITLE
plugins: mtpmount: toggle mount of MTP devices

### PR DESCRIPTION
**Pull request by wustho**
Idk. This might interest someone, at least me.

### CODE REVIEW

**Comment by jarun** [comment]
CI fails. Please check.

**Comment by jarun** [comment]
Still fails:

```
In plugins/mtpmount line 31:
    done <<< ${devs}
         ^-^ SC2039: In POSIX sh, here-strings are undefined.
             ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
    done <<< "${devs}"


In plugins/mtpmount line 45:
    elif [ "$input" -le $(printf "%s\n" "${devs}" | grep -c '^') ]; then
                        ^-- SC2046: Quote this to prevent word splitting.


In plugins/mtpmount line 48:
        while read i; do
              ^--^ SC2162: read without -r will mangle backslashes.


In plugins/mtpmount line 54:
        done <<< ${devs}
             ^-^ SC2039: In POSIX sh, here-strings are undefined.
                 ^-----^ SC2086: Double quote to prevent globbing and word splitting.

Did you mean: 
        done <<< "${devs}"

For more information:
  https://www.shellcheck.net/wiki/SC2039 -- In POSIX sh, here-strings are und...
  https://www.shellcheck.net/wiki/SC2046 -- Quote this to prevent word splitt...
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...

Exited with code exit status 1
```

**Comment by wustho** [comment]
Yup sorry just learning about POSIX... Too much too long spoiled by Bash...

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
