### PR TITLE
Added plugin usermount

### PR DESCRIPTION
**Pull request by chrimbo**
The plugin for easy mounting/unmounting of devices/network shares which are in /etc/fstab and have the user option set.

I use this for my network shares on my NAS. They are not automatically mounted on bootup because the NAS isn't always available.

### CODE REVIEW

**Comment by jarun** [comment]
Please try to write this in bash. Python has tons of dependencies.

**Comment by jarun** [comment]
@luukvbaal @N-R-K can you guys try this in sh? Also, do we need it?

**Comment by luukvbaal** [comment]
I don't see the need for such a plugin myself.
I would look into https://wiki.archlinux.org/title/fstab#Automount_with_systemd.

Will allow you to automatically mount a network share when you try to access it.

**Comment by jarun** [comment]
Thanks! Closing this.

**Pull request closed without merging**
