### PR TITLE
Fix bad getplugs script (#370)

### PR DESCRIPTION
**Pull request by annagrram**
Novice mistake. Sorry.

### CODE REVIEW

**Comment by jarun** [comment]
> Sorry.

It's OK. :+1: Definitely nothing to be sorry about. ;)

I think this is required in `suedit` and `fzcd` plugins as well.

**Comment by annagrram** [comment]
> I think this is required in suedit and fzcd plugins as well.

They are already set appropriately.

I don't write shell scripts too often, so when I wrote that part in getplugs, I probably just ran on autopilot and missed that.

**Comment by jarun** [comment]
> I don't write shell scripts too often

Don't worry. I didn't even know how to fix it without googling so I assumed you'll have a better shot at it. I seldom write too complex scripts myself.

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
