### PR TITLE
Install logo to desktop icons

### PR DESCRIPTION
**Pull request by leovilok**
This shows the "n³" icon in application menus, when desktop file is
installed (using `install-desktop` make target).

### CODE REVIEW

**Comment by jarun** [comment]
Let's wait for @0xACE's input on the logo from the discussion. He does have a point.

**Comment by leovilok** [comment]
This works for any logo as long as the files are nammed the same.

**Comment by leovilok** [comment]
@jarun I rebased this on master, this should be good to go.

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
