### PR TITLE
Propose new shortcuts

### PR DESCRIPTION
**Pull request by maximbaz**
My proposal for our discussion in #422 

My objectives:

1. Have Ctrl shortcuts so that nav-as-you-type is as powerful as normal mode.
1. Have Ctrl shortcuts use the same letter as non-Ctrl shortcuts, so that users need to remember less shortcuts (e.g. if shortcut is `p`, the Ctrl shortcut should be `^P`).

With this change:

- `^P, ^V, ^X` are set as twins for `p, v, x`
- `w ^W` is assigned to "Copy/move sel as" as you suggested
- `^O` becomes "Sort toggles" instead of `^T` (rule 2, `o ^O`)
- `^M` becomes "Mark range/clear" instead `^K` (rule 2, `m ^M`)
- `^;` becomes "Plugin" instead `^P` (rule 2, `; ^;`)
- "Delete entry" becomes `^K` (mnemonic: **k**ill file, plus `^K` is quite common for delete line in other apps)
- "Open with..." becomes `^T` (stretched not-really mnemonic: send file **T**O another app) 

I also noticed one more shortcut that requires Shift key: `! Shell`. Although it already has a Ctrl mapping, we could still set an easier shortcut to it? I propose `t` (mnemonic: terminal).

### CODE REVIEW

**Comment by jarun** [comment]
> ^M becomes "Mark range/clear" instead ^K (rule 2, m ^M)

`^M` is `Enter`. :dancing_men: It's OK. People will remember because of the ^J-^K combo.

> Open with..." becomes ^T (stretched not-really mnemonic: send file TO another app)

We're losing it. ;) Let `^O` be as it is. It's standard too.
Maybe we should have t and ^T for sort toggles.

> I also noticed one more shortcut that requires Shift key: ! Shell

Please leave the shell shortcut `!` alone.

> ^; becomes "Plugin" instead ^P (rule 2, ; ^;)

I didn't know it worked! This is nice!

Now all we need to find is something for Delete entry.

**Comment by jarun** [comment]
We have the following as per above:

```
 NAVIGATION
         Up k  Up                PgUp ^U  Scroll up
         Dn j  Down              PgDn ^D  Scroll down
         Lt h  Parent            ~ ` @ -  HOME, /, start, last
     Ret Rt l  Open                    '  First file
         g ^A  Top                     .  Toggle hidden
         G ^E  End                     0  Lock terminal
         b ^/  Bookmark key            ,  Pin CWD
          1-4  Context 1-4       (Sh)Tab  Cycle context
            /  Filter                 ^N  Nav-as-you-type toggle
          Esc  Exit prompt            ^L  Redraw/clear prompt
            ?  Help, conf             ^G  QuitCD
         Q ^Q  Quit                    q  Quit context
 FILES
         o ^O  Open with...            n  Create new/link
         f ^F  File details            d  Detail view toggle
           ^R  Rename/dup              r  Batch rename
            z  Archive entry           *  Toggle exe
     Space ^J  (Un)select           m ^K  Mark range/clear
         p ^P  Copy sel here           a  Select all
         v ^V  Move sel here        w ^W  Copy/move sel as
         x ^X  Delete sel             ^K  Delete entry
         t ^T  Sort toggles            e  Edit sel
 MISC
         ; ^;  Plugin                  =  Launch app
         ! ^]  Shell                   ]  Cmd prompt
            s  Manage session          u  Unmount
            c  Connect remote
```

**Comment by jarun** [comment]
We'll do this - x ^X for delete both cur and sel:

- if no sel, del cur (we already show correct msg)
- if no cur, del sel (we already show correct msg)
- if both present, confirm sel or cur and proceed

**Comment by jarun** [comment]
Archive entry should be just Archive. It handles sel too!

**Comment by jarun** [comment]
Similarly with above proposal for Delete, it would be just Delete.

**Comment by maximbaz** [comment]
it sounds good, feel free to take over and do this in master if you have time, because I'll be able to get back to this only in the evening

**Comment by jarun** [comment]
No probs. I'll work on it. Please review when you are back.

**Comment by jarun** [comment]
I have made the changes. tehre's a small problem. In filterentries() if I press `^;` it is captured as `;`. Can you please check?

**Comment by jarun** [comment]
However, `getch()` in nextsel() works fine. Does `get_wch()` have any issue?

**Comment by jarun** [comment]
There is no `^;`... it comes as `;`.

**Comment by jarun** [comment]
I think we can settle with:

D - file details
f ^F - Fire plugin

**Pull request closed without merging**
