### PR TITLE
Detach process with F_NOWAIT

### LINKED ISSUE #449: xdg-open zombies
Opening any files via `xdg-open` leaves the `xdg-open` behind as a zombie process after the launched process finished. The `xdg-open` zombies are cleaned up only after `nnn` exited.

For example, here is the result after clicking on a few files (.pdf, .mp4 etc.), viewing finshed, `nnn` still running.

> `% ps x | grep xdg-op`
  `90044 ?        Zs     0:00 [xdg-open] <defunct>`
  `90146 ?        Zs     0:00 [xdg-open] <defunct>`
  `90247 ?        Zs     0:00 [xdg-open] <defunct>`

#### Environment details (Put `x` in the checkbox along with the information)

[x] Operating System: archlinux
[x] Desktop Environment: x11
[x] Terminal Emulator: any (urxvt, termite, ...)
[x] Shell: bash, zsh
[ ] Custom desktop opener (if applicable):
[x] Issue exists on `nnn` master

### PR DESCRIPTION
**Pull request by KlzXS**
Fixes #449 and #227

### CODE REVIEW

**Comment by jarun** [comment]
I'll have to test this and confirm.

**Comment by KlzXS** [comment]
Sure.

**Comment by jarun** [comment]
Can you please rebase once? I made a force push as I wanted to keep the PCRE implementation in one piece. It's experimental and I'm already hating it.

**Comment by jarun** [comment]
The patch seems to be working fine. I will test some more tomorrow my time.

**Comment by KlzXS** [comment]
Please try not to force push. I almost force pushed to your master twice :)

**Comment by jarun** [comment]
The reason I force-pushed is I wanted to @annagrram to have a look at the PCRE implementation. You are already busy with multiple things.

But yes, I'll have this in mind.

**Comment by jarun** [comment]
Thank you! Works fine for me!

**Pull request merged**
