### PR TITLE
Add patch conflict instructions

### PR DESCRIPTION
**Pull request by luukvbaal**
Add instructions and `--merge` flag in `Makefile` to make the steps required somewhat simpler.

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by N-R-K** [comment]
If `--merge` requires GNU patch, wouldn't it be better not to use it in the Makefile?

**Comment by luukvbaal** [comment]
Yeah I guess so. We can revert and update the instructions.

**Comment by N-R-K** [comment]
Have the following macro in the Makefile, `PATCH_OPTS` and have it be empty by default. And then in the ci invoke make as `make PATCH_OPTS="--merge"`. Which I think should do what we're trying to do without making GNU patch a build time dep.

**Pull request merged**
