### PR TITLE
Use spaces in helpstr format

### PR DESCRIPTION
**Pull request by toddyamakawa**
Any objections to using spaces for the `helpstr`? To me it's a lot harder to read the code and modify the help menu with the % modifiers than just using spaces.

### CODE REVIEW

**Comment by jarun** [comment]
To keep the binary size smaller. Also, it's frozen for a while so probably use your patch locally.

**Comment by KlzXS** [comment]
> To keep the binary size smaller

Does it really matter that much? With this patch:

```diff
diff --git a/src/nnn.c b/src/nnn.c
index 15857cf..4215988 100644
--- a/src/nnn.c
+++ b/src/nnn.c
@@ -4574,43 +4574,43 @@ static void show_help(const char *path)
 {
 	int fd;
 	FILE *fp;
-	const char *start, *end;
+	const char *start;
 	const char helpstr[] = {
-		"0\n"
-		"1NAVIGATION\n"
-	       "9Up k  Up%-16cPgUp ^U  Scroll up\n"
-	       "9Dn j  Down%-14cPgDn ^D  Scroll down\n"
-	       "9Lt h  Parent%-12c~ ` @ -  HOME, /, start, last\n"
-	   "5Ret Rt l  Open%-20c'  First file/match\n"
-	       "9g ^A  Top%-21c.  Toggle hidden\n"
-	       "9G ^E  End%-21c+  Toggle auto-advance\n"
-	       "9b ^/  Bookmark key%-12c,  Mark CWD\n"
-		"a1-4  Context 1-4%-7c(Sh)Tab  Cycle context\n"
-		"aEsc  Send to FIFO%-11c^L  Redraw\n"
-		  "cQ  Pick/err, quit%-9c^G  QuitCD\n"
-	          "cq  Quit context%-6c2Esc ^Q  Quit\n"
-		  "c?  Help, conf\n"
-		"1FILTER & PROMPT\n"
-		  "c/  Filter%-12cAlt+Esc  Clear filter & redraw\n"
-		"aEsc  Exit prompt%-12c^L  Clear prompt/last filter\n"
-		 "b^N  Toggle type-to-nav%-0c\n"
-		"1FILES\n"
-	       "9o ^O  Open with...%-12cn  Create new/link\n"
-	       "9f ^F  File details%-12cd  Detail mode toggle\n"
-		 "b^R  Rename/dup%-14cr  Batch rename\n"
-		  "cz  Archive%-17ce  Edit file\n"
-		  "c*  Toggle exe%-14c>  Export list\n"
-	   "5Space ^J  (Un)select%-7cm ^Space  Mark range/clear sel\n"
-	          "ca  Select all%-14cA  Invert sel\n"
-	       "9p ^P  Copy sel here%-8cw ^W  Cp/mv sel as\n"
-	       "9v ^V  Move sel here%-11cE  Edit sel\n"
-	       "9x ^X  Delete\n"
-		"1MISC\n"
-	      "8Alt ;  Select plugin%-11c=  Launch app\n"
-	       "9! ^]  Shell%-19c]  Cmd prompt\n"
-		  "cc  Connect remote%-10cu  Unmount remote/archive\n"
-	       "9t ^T  Sort toggles%-12cs  Manage session\n"
-		  "cT  Set time type%-11c0  Lock\n"
+		"\n"
+		" NAVIGATION\n"
+		"         Up k  Up                PgUp ^U  Scroll up\n"
+		"         Dn j  Down              PgDn ^D  Scroll down\n"
+		"         Lt h  Parent            ~ ` @ -  HOME, /, start, last\n"
+		"     Ret Rt l  Open                    '  First file/match\n"
+		"         g ^A  Top                     .  Toggle hidden\n"
+		"         G ^E  End                     +  Toggle auto-advance\n"
+		"         b ^/  Bookmark key            ,  Mark CWD\n"
+		"          1-4  Context 1-4       (Sh)Tab  Cycle context\n"
+		"          Esc  Send to FIFO           ^L  Redraw\n"
+		"            Q  Pick/err, quit         ^G  QuitCD\n"
+		"            q  Quit context      2Esc ^Q  Quit\n"
+		"            ?  Help, conf\n"
+		" FILTER & PROMPT\n"
+		"            /  Filter            Alt+Esc  Clear filter & redraw\n"
+		"          Esc  Exit prompt            ^L  Clear prompt/last filter\n"
+		"           ^N  Toggle type-to-nav\n"
+		" FILES\n"
+		"         o ^O  Open with...            n  Create new/link\n"
+		"         f ^F  File details            d  Detail mode toggle\n"
+		"           ^R  Rename/dup              r  Batch rename\n"
+		"            z  Archive                 e  Edit file\n"
+		"            *  Toggle exe              >  Export list\n"
+		"     Space ^J  (Un)select       m ^Space  Mark range/clear sel\n"
+		"            a  Select all              A  Invert sel\n"
+		"         p ^P  Copy sel here        w ^W  Cp/mv sel as\n"
+		"         v ^V  Move sel here           E  Edit sel\n"
+		"         x ^X  Delete\n"
+		" MISC\n"
+		"        Alt ;  Select plugin           =  Launch app\n"
+		"         ! ^]  Shell                   ]  Cmd prompt\n"
+		"            c  Connect remote          u  Unmount remote/archive\n"
+		"         t ^T  Sort toggles            s  Manage session\n"
+		"            T  Set time type           0  Lock\n"
 	};
 
 	fd = create_tmp_file();
@@ -4630,18 +4630,7 @@ static void show_help(const char *path)
 		pipetof("fortune", fp);
 #endif
 
-	start = end = helpstr;
-	while (*end) {
-		if (*end == '\n') {
-			snprintf(g_buf, CMD_LEN_MAX, "%*c%.*s",
-				 xchartohex(*start), ' ', (int)(end - start), start + 1);
-			fprintf(fp, g_buf, ' ');
-			start = end + 1;
-		}
-
-		++end;
-	}
-
+	fprintf(fp, "%s", helpstr);
 	fprintf(fp, "\nVOLUME: %s of ", coolsize(get_fs_info(path, FREE)));
 	fprintf(fp, "%s free\n\n", coolsize(get_fs_info(path, CAPACITY)));
```

I only see an increase of 56 bytes on my end. And I would say you get cleaner looking code for it.

**Comment by jarun** [comment]
I'll get back on this guys.

**Comment by KlzXS** [comment]
Sure thing, take your time this can wait.

**Comment by jarun** [comment]
@KlzXS I tried your patch and I don't see any visual difference and you are probably right that the size difference is negligible.

However, I remember we had been using spaces before and we moved to the current way when we found that adding an extra space per line of help was adding _significantly_ to binary size. I think right now we are good with what we have. So far I haven't seen @toddyamakawa add any option to the help and I don't think that's going to happen frequently in the future. With that in mind, I don't want to change the help format right away. This will remain open and if we see several new additions to help we will revisit.

**Comment by KlzXS** [comment]
I feel this is pushing it, but keep in mind that using spaces allows you to have a single call to `fprintf` instead of what we have now.

But at the very least could we format the string to represent what will be printed in the end. I find the current indentation quite arbitrary. `0` `1` and `a` are all on the same indentation level. Or am I missing something?

**Comment by jarun** [comment]
> I find the current indentation quite arbitrary. 0 1 and a are all on the same indentation level.

Fixed the alignment at commit 118657020e43fa75ab89bada281a7d9f25d69684.

**Pull request closed without merging**
