### PR TITLE
Use HTTPS everywhere (mechanical edit using util from https-everywhere)

### PR DESCRIPTION
**Pull request by ypid**
```Shell
~/src/EFForg/https-everywhere/utils/rewriter/rewriter.js .
```

Ref: https://github.com/EFForg/https-everywhere/tree/master/utils/rewriter

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by 0xACE** [comment]
I don't have the tools needed to interpret `*.hvif`, could anyone clarify that it's the intended change?

`git diff --binary origin/master..origin/master~1` wasn't helpful

**Comment by jarun** [comment]
I will remove it and it will be a forced update.

**Comment by jarun** [comment]
@ypid can you explain what that file contains?

**Comment by jarun** [comment]
@0xACE many thanks for keeping your eyes open. :+1:

**Comment by ypid** [comment]
> @ypid can you explain what that file contains?

I did not check. Honestly, it slipped my review. I am in the process of making the rewrite script better handle binary files, ref: https://github.com/EFForg/https-everywhere/pull/19869. Thanks for fixing it.

**Comment by jarun** [comment]
@ypid no problem!

**Pull request merged**
