### PR TITLE
Fixed wrong mode while creating new file #1853

### PR DESCRIPTION
**Pull request by Taraxtix**

### CODE REVIEW

**Comment by Taraxtix** [comment]
On the issue #1853, it is mentioned that there `touch` produces those permissions on new file : `-rw-r--r--`
Mine actually produces those ones : `-rw-rw-r--`.
In my fix I have make so that it produces permission like my `touch` command does.

**Review by cor — APPROVED** [review]

**Comment by jarun** [comment]
Please have it as a local patch.

**Comment by Taraxtix** [comment]
> Please have it as a local patch.

I'm not sure if this comment is for me or your co-workers 😅

**Comment by KlzXS** [comment]
@Taraxtix he means keep maintaining it as a local patch for yourself. We won't be implementing this.

**Pull request closed without merging**
