### PR TITLE
CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by marioortizmanero**
I'm a recent contributor so I'm not really sure what else I should add here. @jarun, you should take a look and see if you'd like anything else to be noted in `CONTRIBUTING.md`

### CODE REVIEW

**Comment by jarun** [comment]
Thank you! This is good.

**Comment by leovilok** [comment]
This is very valuable!

I won't use Gitter because I avoid web bloat (a single Gitter tab use way more memory than a `nnn` instance, but I guess I could use their IRC backend) and centralized closed remote services (GitHub is the same, but it's not a reason to use an other one).
But have fun using it!

A lot of project use Gitter badges (like that: [Gitter chat](https://gitter.im/jarun/nnn)), this might be added to the global `README.md`. Source:
~~~md
[![Gitter chat](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/jarun/nnn)
~~~

**Comment by marioortizmanero** [comment]
Should I add a note that there's also an IRC backend available, for those who don't know? I'm not sure how it works so it'd be best if you did that yourself.

**Comment by leovilok** [comment]
Well it's mentionned on gitter's front page, so I guess it's OK.

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
This is now linked from the ToDo list, right below the ToDos. :+1:

**Pull request merged**
