### PR TITLE
fix shellcheck issues

### PR DESCRIPTION
**Pull request by N-R-K**

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

Is shellcheck not running on PRs? The earlier PR passed.

**Comment by KlzXS** [comment]
I think it sometimes asks for approval. I don't know what that's about

**Comment by jarun** [comment]
okk

**Comment by N-R-K** [comment]
> I think it sometimes asks for approval. I don't know what that's about

I think that's only for "first time contributors" ? I don't think it matters for us since we don't have any "secret" in our CI.

**Pull request merged**
