### PR TITLE
plugin: cleanfilename: clean filename to be more shell-friendly

### PR DESCRIPTION
**Pull request by wustho**
Basically renaming file/dir to be more shell friendly by replacing spaces and any other non-A-Za-z0-9.- char with underscore ().

eg. '[qwer] sfasdf.txt' --> '_qwer__sfasdf.txt'

### CODE REVIEW

**Comment by wustho** [comment]
Forgot description. Here is one:

Basically renaming file/dir to be more shell friendly by replacing spaces and any other non-A-Za-z0-9._- char with underscore (-).

eg. '[qwer] sfasdf.txt' --> '_qwer__sfasdf.txt'

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
Does it handle escape sequences a well? How about single/double quotes?

**Comment by jarun** [comment]
@wustho can you please respond to my questions above?

In addition, does it remove leading and trailing spaces?

**Comment by wustho** [comment]
@jarun hey there, sorry just read my email...

It should handle escape sequence and and single/double quotes as well...

About leading, or trimming, it wont remove them but instead replace them with _. I change IFS to newline and split selection by nullbytes. So `'  qwe  '` will be `'__qwe__'`...

In the cost that it can't handle new line...

**Comment by jarun** [comment]
Please add these finer details to the plugin. Users may assume something else and misuse.

**Comment by wustho** [comment]
Sorry, @jarun , any idea how can I put those details into words? English is not my first lang...

**Comment by wustho** [comment]
Ok, I'll try later... I think we could make it to handle newline also, but it's inefficient to do it with posix sh... Array will totally helps.

**Comment by jarun** [comment]
Feel free to move to bash and use array. Please ensure the documentation is accurate.

**Pull request merged**
