### PR TITLE
Misc cleanups

### PR DESCRIPTION
**Pull request by N-R-K**
A couple small changes to get rid of some unnecessary code, no changes in functionality intended:

* Fix an incorrect comment on `xmemrchr()`.
* Use designated initializer instead of initializing `cfg` manually.
* Initialize to 0 instead of `memset`-ing to 0.

### CODE REVIEW

**Comment by N-R-K** [comment]
I'll fix the patches in a bit. Also don't think it's a good idea for the patches CI to abort on first failure, we want it to print out all the failing patches before aborting. Will look into fixing that as well.

**Comment by jarun** [comment]
Neat!
Patching fails on CI. Please have a look.

**Comment by luukvbaal** [comment]
> I'll fix the patches in a bit. Also don't think it's a good idea for the patches CI to abort on first failure, we want it to print out all the failing patches before aborting. Will look into fixing that as well.

Definitely. Would be great if we could expose the patch ci to the developer in the Makefile somehow. I.e. running `make patches` will ideally compile all the patches (not aborting on fail, if possible). Might make it easier to confirm patches are still working locally.

**Comment by N-R-K** [comment]
> Patching fails on CI. Please have a look.

Done.

>  Would be great if we could expose the patch ci to the developer in the Makefile somehow. I.e. running make patches will ideally compile all the patches (not aborting on fail, if possible).

Yeah, that sounds great. I think it can be done easily by extracting the script from the CI's yaml to a bash script so that it can be invoked both from the Makefile and the run in the ci.

**Comment by jarun** [comment]
I am fine with what you guys decide.

**Comment by jarun** [comment]
Make it easy for the dev to replicate the failure, but please don't remove the CI failure. Otherwise, the issue might be ignored.

**Comment by jarun** [comment]
Thank you!

**Comment by N-R-K** [comment]
Note that we need to run `git restore src` so that it can clean up the src after a patch fails so that subsequent patches don't automatically fail due to dirty src.

**Comment by N-R-K** [comment]
Updated version which exits with the proper exit code: 

```bash
#!/bin/bash

export PATCH_OPTS="--merge"
patches=("O_GITSTATUS" "O_NAMEFIRST" "O_RESTOREPREVIEW")
z=$(( 1 << ${#patches[@]} ))
pid=$$
ret=0
trap 'ret=1' SIGUSR1

for ((n=1; n < z; ++n)); do
    for ((i=0; i < ${#patches[@]}; ++i)); do
        printf "%s=%d " "${patches[$i]}" "$(( (n & (1 << i)) != 0 ))"
    done | tee "/dev/stderr" | (
        make clean -s
        xargs make 2>&1
        if [ "$?" -ne 0 ]; then
            echo "[FAILED]" >&2
            kill -SIGUSR1 "$pid"
        else
            echo "[SUCCESS]" >&2
        fi
        git restore src
    ) >/dev/null
done
exit "$ret"
```

We can try to put this into the Makefile if you prefer that @luukvbaal . But afaik by default make invokes `/bin/sh` which might not be bash, so we'll need to avoid any bash-ism if we want the Makefile to be portable. Which is why I opted for a separate script which invokes bash specifically.

**Pull request merged**
