### PR TITLE
Ignore NOLC when ICONS/NERD are set

### PR DESCRIPTION
**Pull request by luukvbaal**
Should prevent the situation in #1026. Please suggest the info message format you prefer @jarun if you want this in.

### CODE REVIEW

**Comment by luukvbaal** [comment]
Working on it...

**Comment by jarun** [comment]
Please confirm when done.

**Comment by luukvbaal** [comment]
Should be good now

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
@luukvbaal we missed the Haiku Makefile. Please update that one as well.

**Comment by luukvbaal** [comment]
My bad, made the PR

**Comment by jarun** [comment]
No problem!

**Comment by mohammad5305** [comment]
> @luukvbaal we missed the Haiku Makefile. Please update that one as well.

same happened 
I compile with flag make O_NERD=1 or make O_ICONS=1 but nothing change

**Pull request merged**
