### PR TITLE
preview-tui: ensure 1st hovered file is previewed

### PR DESCRIPTION
**Pull request by leovilok**
@jarun This should fix the remaining issue discussed in #559

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
After merging this I remembered you wanted to use your full name. Please update in next PR.

**Comment by leovilok** [comment]
@jarun I'll do that next time I touch `preview-tabbed`

**Comment by jarun** [comment]
Sure thing!

**Pull request merged**
