### PR TITLE
Improve patches ci

### PR DESCRIPTION
**Pull request by N-R-K**
Goes through all different combinations automatically and adding another patch should be just as easy as putting the name into the `patches` array. Perhaps not a big deal doing it manually atm since there's only 3 patches /shrug.

### CODE REVIEW

**Review by luukvbaal — APPROVED** [review]

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
I see the following error in CI:

```
Run patches=("O_GITSTATUS" "O_NAMEFIRST" "O_RESTOREPREVIEW")
O_GITSTATUS=1 O_NAMEFIRST=0 O_RESTOREPREVIEW=0 
rm -f -f nnn nnn-4.5.tar.gz *.sig nnn-static nnn-static-4.5.x86_64.tar.gz nnn-icons-static nnn-icons-static-4.5.x86_64.tar.gz nnn-nerd-static nnn-nerd-static-4.5.x86_64.tar.gz nnn-emoji-static nnn-emoji-static-4.5.x86_64.tar.gz nnn-musl-static nnn-musl-static-4.5.x86_64.tar.gz
patch: unrecognized option `--merge'
patch: Try `patch --help' for more information.
make[1]: *** [prepatch] Error 2
make: *** [nnn] Error 2
Error: Process completed with exit code 1.
```

**Comment by luukvbaal** [comment]
@jarun see #1379, alternatively we could `brew install gpatch` on `macOS-latest`. I'm not aware if we have a strong preference for running ci on macOS.

**Comment by jarun** [comment]
No, we are fine on Ubuntu.

**Pull request merged**
