### PR TITLE
preview-tui: fix tmux behaviour, del refs to nuke

### PR DESCRIPTION
**Pull request by leovilok**
As reported by @toddyamakawa

### CODE REVIEW

**Comment by jarun** [comment]
Thanks guys! :+1:

**Comment by jarun** [comment]
@leovilok just checked this out! very useful indeed.

A problem I am seeing with this (using tmux): when I start the plugin, the currently hovered file is not shown (but the new tmux pane is created). When I scroll up and down I can see the previews.

**Comment by jarun** [comment]
And that's probably with text files only. Hover on Makefile or README.md, then launch the plugin and you'll probably see it. Works fine when starting hovered on an image.

**Comment by leovilok** [comment]
At the moment, we need a call to `move_cursor` to send the first write to the FIFO. Any resize/actual cursor move should do, there might be a redraw after plugin call, but it's sometimes too early (the plugin didn't open the FIFO yet).

I could pass `$nnn` to the previewer, to make sure the first file is displayed, I'll see if it's not too much code added.

**Comment by jarun** [comment]
The hovered file is always passed to a plugin by design:

https://github.com/jarun/nnn/tree/master/plugins#access-level-of-plugins

**Comment by jarun** [comment]
BTW, the other plugin `preview-tabbed` works as expected.

**Pull request merged**
