### PR TITLE
change ^ v to unicode arrows

### PR DESCRIPTION
**Pull request by luukvbaal**
Wondering if this can be done harmlessly. I tested ~20 fonts on my system which all included this unicode character, including linux tty font.

### CODE REVIEW

**Comment by KlzXS** [comment]
CI says that makes the function too complex. I wouldn't argue against that assertion.

We use ncursesw so it should be able to handle unicode string just fine. But do see what you can do about the failing CI to "simplify" `browse()`.

**Comment by luukvbaal** [comment]
> CI says that makes the function too complex. I wouldn't argue against that assertion.
> 
> We use ncursesw so it should be able to handle unicode string just fine. But do see what you can do about the failing CI to "simplify" `browse()`.

Not sure what to do about it, this change doesn't affect the `browse()` function does it? It's in the `redraw()` function.

**Comment by KlzXS** [comment]
Huh, you are right. I guess it calculates complexity in depth. Still, it should be resolved. And fixing up `browse()` is definetly welcome.

From the first moment I saw the 1500 line switch I didn't like it, but I don't have anything that would simplify it without impacting the binary size.

**Comment by luukvbaal** [comment]
> Huh, you are right. I guess it calculates complexity in depth. Still, it should be resolved. And fixing up `browse()` is definetly welcome.
> 
> From the first moment I saw the 1500 line switch I didn't like it, but I don't have anything that would simplify it without impacting the binary size.

Has nothing to do with depth complexity or this commit, the statements threshold was exceeded in https://github.com/jarun/nnn/commit/9c218d41e8d75c43516b51379c1dd4564378b045. I suppose a rewrite of `browse()` is indeed in order if we want to pass the complexity test.

**Comment by luukvbaal** [comment]
I did find some fonts which don't contain this unicode arrow so I guess this is a no go. Unless we can somehow determine the active font and whether it supports the unicode character.

**Comment by luukvbaal** [comment]
Checking whether a font supports the glyph is quite trivial with `fontconfig`, determining the active font terminal I'm not so sure about.

**Comment by luukvbaal** [comment]
Doesn't seem to be possible without additional dependencies. It's possible with `lsof` and `sed` but I doubt we will want to require `lsof` as a dependency.

Closing unless we want to accept that users with an (uncommon) font not supporting the arrow will see nothing.

**Comment by jarun** [comment]
I remember we used these in help in earlier versions and had issues on *bsd where the binary was detected as rogue (?). @annagrram found it.

**Comment by jarun** [comment]
Commit 0144f440609b4fb7dcdf9e3325e6d1de3e6085bf.

**Pull request closed without merging**
