### PR TITLE
Kill kitty icat in preview-tui

### PR DESCRIPTION
**Pull request by luukvbaal**
Should fix https://github.com/jarun/nnn/issues/935#issuecomment-840850150.

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by luukvbaal** [comment]
@Kabouik did you see https://github.com/jarun/nnn/issues/935#issuecomment-840937419? Can you confirm that this commit fixed the queuing issue?

**Comment by Kabouik** [comment]
Thanks a lot @luukvbaal. I still observe some queuing when holding down <kbd>Up<kbd> or <kbd>Down<kbd> with kitty's `icat` even on my PC. I haven't pulled master on the phone yet but that should be the same.

I'm happy to try `ueberzug` if it performs better (damn, I just spent a few hours during the last two days to configure my `kitty.conf` and finally have image previews in my terminal thanks to `icat`, I didn't know performance was notoriously bad compared to alternatives!). However I think right now `preview-tui*` prioritizes kitty's `icat` if available. We might want to change that if `ueberzug` is also installed and performs better, no?

**Comment by luukvbaal** [comment]
How does the queuing manifest? For me when I hold down <kbd>Down</kbd> in `kitty`, nothing is drawn by `icat` until I release <kbd>Down</kbd> i.e. the preview window stays empty. I don't experience any queuing of previews as before this commit.

Not sure, people using `kitty` will probably expect image previews to be handled by `icat`. Your best bet would probably to switch to something like `alacritty` if you want to use `ueberzug` previews. 

On the other hand, if the user indeed installed `ueberzug` I suppose we might also reasonably expect them to want `ueberzug` previews in `kitty`. Would need feedback from `kitty` for such a change. Otherwise, just move the `ueberzug` if clause above `kitty` in `image_preview` youself.

**Comment by jarun** [comment]
> Otherwise, just move the ueberzug if clause above kitty in image_preview youself.

This. Once again, plugins are indicative.

**Comment by Kabouik** [comment]
That's totally fine by me, no worries. I was just wondering if kitty users who also have installed `ueberzug` may be intersted in using it by default since it performs better. On the other hand, they may also have installed it to have image support in other terminal emulators but still prefer to use `icat` when in kitty, I don't know.

This is what the queuing looks like on my end (in `icat`) even after the changes of this PR:

https://user-images.githubusercontent.com/7107523/118283663-21938000-b4bf-11eb-86e8-8226a439d490.mp4

This is on a PC with hardware acceleration here (the queuing is obviously more severe on the slow machine with no hardware acceleration).

**Comment by Kabouik** [comment]
Nevermind, there are conflicts on my machine between my ongoing PR and yours here, which I hadn't noticed. This is the cause.

**Pull request merged**
