### PR TITLE
Addressing #489

### PR DESCRIPTION
**Pull request by KlzXS**
Can we keep this open until we close the issue?

### CODE REVIEW

**Comment by jarun** [comment]
Sure!

**Comment by jarun** [comment]
I am merging this after good amount of testing. if something new comes up, we'll handle it in new PR.

**Comment by jarun** [comment]
Also, for now, let the prints be on.

**Comment by KlzXS** [comment]
> Also, for now, let the prints be on.

What prints?

**Comment by jarun** [comment]
```
'./nnn' -> './nnn1'
'./nnn.1' -> './nnn.11'
'./plugins' -> './plugins1'
'./plugins' => './plugins1'
'./README.md' -> './README.md1'
```

**Comment by KlzXS** [comment]
vidir called them a feature and I couldn't be bothered to implement a flag for them. Also they are handy as a debug print. So yeah, we can remove them later.

**Comment by jarun** [comment]
```
'./plugins' -> './plugins1'
'./plugins' => './plugins1'
```

what's the difference?

**Comment by KlzXS** [comment]
The one with `=>` prints only if the entry moved was a directory. Not sure why in that case `->` is also printed.

**Comment by jarun** [comment]
I think we can leave it as it is for now.

**Pull request merged**
