### PR TITLE
Bring back plain builds

### PR DESCRIPTION
**Pull request by jarun**
Resurrect:

1. OS X build
2. Build with flag `-Werror`

### CODE REVIEW

**Comment by fennm** [comment]
Nice solution!

**Comment by jarun** [comment]
Thanks! We need the original builds... I don't own a Mac and @zmwangx is quite busy already, I remain hesitant to poke him except really necessary.

**Comment by zmwangx** [comment]
Um, anything I can help with here?

**Comment by jarun** [comment]
No, I got it now! Thanks for your guidelines. :dancing_men:

**Comment by zmwangx** [comment]
Sweet. Feel free to ping me.

**Pull request merged**
