### PR TITLE
Wait until cmus is ready and fix fzplug preview command

### PR DESCRIPTION
**Pull request by luukvbaal**
Fix issues mentioned in https://github.com/jarun/nnn/pull/1010#issuecomment-841713987

### CODE REVIEW

**Comment by jarun** [comment]
Thank you!

**Comment by Kabouik** [comment]
Thanks!

**Comment by Kabouik** [comment]
Although this improved the code a lot, there is one relatively minor drawback to using a single `$plugin` command. The `fzf` `:wrap` option is now enforced whether `bat` is detected or not, even though `bat` does a better job when it knows the terminal width. The prior version used `:wrap` only for the `cat` variant.

See comparison (master on the left, previous commit on the right):

Screenshot_20210515_001

**Comment by Kabouik** [comment]
For this particular plugin, removing `bat` line numbers would help:

Screenshot_20210515_002

No real need to show line numbers in plugins a user is about to execute (and not to edit) anyway.

**Comment by luukvbaal** [comment]
Agreed, I would also just get rid of the wrap option for `fzf`

**Comment by Kabouik** [comment]
With no `:wrap`, some plugin descriptions may be unreadable depending on the window size. I found myself using new plugins much more frequently since `fzfplug` due to the `fzf` preview pane.

**Comment by jarun** [comment]
@luukvbaal and @Kabouik are you guys familiar with vimscript?

**Comment by luukvbaal** [comment]
I guess, to me a preview window is not meant for actual reading but rather just for a quick glance at the context. Line wrapping only makes it harder to read to my eyes.

**Comment by luukvbaal** [comment]
Not particularly well versed in it @jarun. I know about the open issues for `nnn.vim` though, I'll take a look if I ever I feel like it.

**Comment by jarun** [comment]
OK thanks!

**Comment by Kabouik** [comment]
> I guess, to me a preview window is not meant for actual reading but rather just for a quick glance at the context. Line wrapping only makes it harder to read to my eyes.

I agree to some extent but I see `fzplug` as a script launcher/explorer and I am not necessarily familiar with those scripts since I haven't authored them. `fzplug` doesn't offer a shortcut to edit/view the scripts, as opposed to files previewed with `preview-tui*` that can be opened with just a keystroke, therefore exhaustive preview means discoverability for me in that case.

**Comment by jarun** [comment]
No problem!

**Pull request merged**
