### PR TITLE
plugins for integration with MacOS clipboard

### LINKED ISSUE #1723: Plugins for integration with MacOS clipboard
Implement plugins to support file copy and paste operation from MacOS clipboard. This will help sharing files between `nnn` and other programs like Email, Slack, Finder etc. 

There is a drag and drop plugin which caters for this requirement on linux but nothing is available for MacOS that allows the use of `nnn` with other GUI applications (as far as I can see).

### PR DESCRIPTION
**Pull request by umaranis**
resolves #1723

### CODE REVIEW

**Comment by jarun** [comment]
Why can;t this be integrated in existing plugin `.cbcp`?

Also, CI fails:

```
########## shellcheck ##########

In plugins/cbcopy-mac line 1:
#!/usr/bin/osascript
^-- SC1008 (error): This shebang was unrecognized. ShellCheck only supports sh/bash/dash/ksh. Add a 'shell' directive to specify.


In plugins/cbcopy-mac line 12:
  set filePath to (second item of args & "/" & first item of args)
      ^------^ SC2121 (warning): To assign a variable, use just 'var=value', no 'set ..'.
                  ^-- SC1036 (error): '(' is invalid here. Did you forget to escape it?
                  ^-- SC1088 (error): Parsing stopped here. Invalid use of parentheses?


In plugins/cbpaste-mac line 12:
fs=($( osascript -e "use framework \"Foundation\"
   ^-- SC3030 (warning): In POSIX sh, arrays are undefined.
    ^-- SC2207 (warning): Prefer mapfile or read -a to split command output (or quote to avoid splitting).


In plugins/cbpaste-mac line 23:
cp -R "${fs[@]}" "$2/"
       ^------^ SC3054 (warning): In POSIX sh, array references are undefined.

For more information:
  https://www.shellcheck.net/wiki/SC1008 -- This shebang was unrecognized. Sh...
  https://www.shellcheck.net/wiki/SC2121 -- To assign a variable, use just 'v...
  https://www.shellcheck.net/wiki/SC2207 -- Prefer mapfile or read -a to spli...

Exited with code exit status 1
```

**Comment by umaranis** [comment]
If you understand if correctly, the `.cbcp` plugin copies the paths of selected files into the clipboard whereas my plugins copy/paste actual files. Not sure how the two can be integrated.

I think the pipeline is failing because these script can only run on macos (not on linux).

**Comment by jarun** [comment]
I see. In that case, fine.

In that case, please ignore shellcheck for these files.

**Comment by umaranis** [comment]
@jarun shellcheck is ignored now for these plugins

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
