### PR TITLE
Fix #974: picker mode broken

### LINKED ISSUE #974: picker mode broken
#918 is open again on master when using `NNN_OPTS=x` in picker mode. 
It would be nice to make picker mode work with this option set

### PR DESCRIPTION
**Pull request by luukvbaal**

### CODE REVIEW

**Comment by luukvbaal** [comment]
On second thought just add back the `g_state.picker` test, retaining the other X functionality in picker mode.

**Comment by jarun** [comment]
> On second thought just add back the g_state.picker test, retaining the other X functionality in picker mode.

Yes, just block the print.

**Comment by jarun** [comment]
I will take care of the check. Thanks!

**Comment by jarun** [comment]
Ahh OK. Ignore my comment. We are good as the X11 tweaks are not in the same place.

**Pull request merged**
