### PR TITLE
preview-tui demo

### PR DESCRIPTION
**Pull request by luukvbaal**

### CODE REVIEW

**Comment by jarun** [comment]
Is it playing correctly for you? I don;t see the image previews...

**Comment by luukvbaal** [comment]
Uhm yeah playing fine here

**Comment by jarun** [comment]
I think we can do this -> use the previous 2.32 MB gif, but use an image with an arrow on it to indicate that clicking on it would take you to the demo.

**Comment by jarun** [comment]
That way, the image will render faster on the page and interested people can click on it to view the demo.

**Comment by luukvbaal** [comment]
Fine I'll do that tommorow, It's late here hehe.

**Comment by jarun** [comment]
I'm reverting the earlier commits. Please don't self merge.

**Pull request merged**
