### PR TITLE
Make batchrename interactive

### PR DESCRIPTION
**Pull request by KlzXS**
Added the requested improvement. We no longer ignore `stderr` output from `mv` as that is what is used to display the overwrite prompts.

Please confirm that it works as expected.

### CODE REVIEW

**Comment by KlzXS** [comment]
Should we do `.nmv` plugin as well?

**Comment by jarun** [comment]
Yes, we should have this for `.nmv` too.

**Comment by jarun** [comment]
Please update this PR.

**Comment by jarun** [comment]
Thank you!

**Pull request merged**
