### PR TITLE
add support for previewing pngs in preview-tui

### PR DESCRIPTION
**Pull request by PatrickF1**
tested this locally

### CODE REVIEW

**Comment by luukvbaal** [comment]
Have you tried previewing a png without this change? Should work fine as it's handled by https://github.com/jarun/nnn/blob/bd6e7e81479823fdf28cdc507027982011039c9f/plugins/preview-tui#L230

**Comment by PatrickF1** [comment]
Interesting. Maybe I'm missing one of the deps my screen is definitely empty!

**Comment by luukvbaal** [comment]
The point of `generate_preview` is that it converts images to jpg as it is faster to preview. This does indeed require a dependency (ImageMagick) however it will fall back to the exact same line executed by this PR so I'm not sure why it wouldn't work for you:
https://github.com/jarun/nnn/blob/bd6e7e81479823fdf28cdc507027982011039c9f/plugins/preview-tui#L363-L367

**Comment by luukvbaal** [comment]
Do you perhaps have a `convert` command in your `PATH` that is not the one from ImageMagick? Only thing I can think of.

**Comment by PatrickF1** [comment]
convert isn't on my path

**Comment by N-R-K** [comment]
You can try removing the null redirections `>/dev/null` around that area to see if anything interesting shows up.

**Comment by PatrickF1** [comment]
Sure I'll try that, thanks!

**Comment by PatrickF1** [comment]
Well, I have truly no idea what happened but after deleting the /dev/null it worked. So then I ran the plugin installer again and it worked. Maybe I had accidentally modified it before and broke it. 🤷‍♂️

**Pull request closed without merging**
