### PR TITLE
Add .gitignore to ignore compilation products

### PR DESCRIPTION
**Pull request by zmwangx**
I'm allergic to dirty worktrees...

### CODE REVIEW

**Comment by zmwangx** [comment]
By the way, mind reminding me why create an `config.h` when it's just a copy of `config.def.h`? 😅

**Comment by jarun** [comment]
Thank you!

**Comment by jarun** [comment]
> By the way, mind reminding me why create an config.h when it's just a copy of config.def.h? ￼

Legacy legacy legacy :+1: 
But I think it would make sense if we remove the config.h removal stuff from the Makefile. Then it would have someone's temp preferences.

**Comment by zmwangx** [comment]
> But I think it would make sense if we remove the config.h removal stuff from the Makefile. 

Makes sense.

**Pull request merged**
