### PR TITLE
new config: detail column order

### PR DESCRIPTION
**Pull request by luukvbaal**
This is my attempt to implement a new config variable to allow setting the order of the columns in detail mode.

Introduces a new environment variable `NNN_DCOLUMNS` to be set by user preferred order of the following characters:
- "n": entry name
- "o": owner:group
- "p": permission bits
- "P": `ls -l` style permissions
- "t": time

I'm not sure about the quality of the code as I had never worked with `ncurses` before. Was hard to wrap my head around the `attr` bitmasks in `printent_long` but I seem to have made it work properly. Although there might be some redundant `attroff`/`attron` calls, not sure.

I did come across #267 (after implementing this) so I'm curious to know if you think this implementation is acceptable. As you said for smaller terminal sizes the name needs to be cropped (could also consider falling back to "p" first when using "P") which is not working properly in this PR.

If that is required before merging I'll take another look at it and any other remarks.

### CODE REVIEW

**Comment by luukvbaal** [comment]
Not sure what kind of rewrite is required to properly crop and restore non detailed view when the terminal gets too small.

I'll look into it myself further but for now this seems to be working fine in large terminals.

**Comment by jarun** [comment]
Please do not make cosmetic changes without a discussion in the ToDo list first.

Did you see the amount of change in this PR? Who is going to maintain this change in the name of flexibility after a year?

**Comment by luukvbaal** [comment]
I thought discussion could be done here, hence the draft PR. Not sure what maintenance is required if implemented properly.

**Comment by jarun** [comment]
We fixed several issues with column length, broken lines etc. So we made a length fixed for fixed columns and a variable field at the end for lengths.

We like to discuss bigger changes first because I personally don;t like contributors to waste their valuable time on things we may not want.

**Comment by luukvbaal** [comment]
Understandable, I hope it's not time wasted given I can properly finish the feature such that it might be merged.

Even if it won't be merged it's already usable for me so it won't totally wasted...

**Pull request closed without merging**
