### PR TITLE
add NNN_ONCHDIR option to handle chdir events

### PR DESCRIPTION
**Pull request by vkochan**
It might be useful (looks like in some special cases)
to have ability of handling dir changes from nnn to make
custom routines (indexing, project pre-init).

Signed-off-by: Vadym Kochan <vadim4j@gmail.com>

### CODE REVIEW

**Comment by 0xACE** [comment]
I think this is too much... Also I think it's better that you use the FIFO pipe and detect directory changes that way, though I'm not sure if that gets triggered when you switch contexts (didn't even check if this PR even handles that itself)...

**Comment by vkochan** [comment]
ok, closing.

**Comment by 0xACE** [comment]
Ah, you can relax with that. I don't make executive decisions. Just voicing my opinion.

My specific conflict with this proposal is running `spawn()` when you run into a new directory, where as the same information can be deduced from the existing `NNN_FIFO`, meaning this is a redundant feature. Though someone who remembers it better than me could probably correct me if I'm wrong.

**Comment by vkochan** [comment]
you are right, fifo writing is better than process spawning, looks like
fifo is enough to implement it.

**Pull request closed without merging**
